exp_name: qtdb/1over4

dataset:
  ecg_dir: ../data/qtdb/ecg
  label_dir: ../data/qtdb/label
  index_dir: ../index/qtdb
  train_unlabeled_csv: QTDB_train_unlabeled.csv
  train_labeled_csv: QTDB_train_labeled_1over4.csv
  valid_csv: QTDB_valid.csv
  test_csv: QTDB_test.csv
