exp_name: zhejiang/1over16

dataset:
  ecg_dir: ../data/zhejiang/ecg
  label_dir: ../data/zhejiang/label
  index_dir: ../index/zhejiang
  train_unlabeled_csv: Zhejiang_train_unlabeled.csv
  train_labeled_csv: Zhejiang_train_labeled_1over16.csv
  valid_csv: Zhejiang_valid.csv
  test_csv: Zhejiang_test.csv
