exp_name: isp/1over16

dataset:
  ecg_dir: ../data/isp/ecg
  label_dir: ../data/isp/label
  index_dir: ../index/isp
  train_unlabeled_csv: ISP_train_unlabeled.pkl
  train_labeled_csv: ISP_train_labeled_1over16.pkl
  valid_csv: ISP_valid.pkl
  test_csv: ISP_test.pkl
