exp_name: cross_domain/merged

dataset:
  ecg_dir: ../data
  label_dir: ../data
  index_dir: ../index/cross_domain
  train_unlabeled_csv: merged_unlabeled.csv
  train_labeled_csv: merged_train_labeled.csv
  valid_csv: merged_valid.csv
  test_csv: merged_test.csv
